# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class AuthGroup(models.Model):
    name = models.CharField(unique=True, max_length=150)

    class Meta:
        managed = False
        db_table = 'auth_group'


class AuthGroupPermissions(models.Model):
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)
    permission = models.ForeignKey('AuthPermission', models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_group_permissions'
        unique_together = (('group', 'permission'),)


class AuthPermission(models.Model):
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING)
    codename = models.CharField(max_length=100)
    name = models.CharField(max_length=255)

    class Meta:
        managed = False
        db_table = 'auth_permission'
        unique_together = (('content_type', 'codename'),)


class AuthUser(models.Model):
    password = models.CharField(max_length=128)
    last_login = models.DateTimeField(blank=True, null=True)
    is_superuser = models.BooleanField()
    username = models.CharField(unique=True, max_length=150)
    first_name = models.CharField(max_length=30)
    email = models.CharField(max_length=254)
    is_staff = models.BooleanField()
    is_active = models.BooleanField()
    date_joined = models.DateTimeField()
    last_name = models.CharField(max_length=150)

    class Meta:
        managed = False
        db_table = 'auth_user'


class AuthUserGroups(models.Model):
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_groups'
        unique_together = (('user', 'group'),)


class AuthUserUserPermissions(models.Model):
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    permission = models.ForeignKey(AuthPermission, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_user_permissions'
        unique_together = (('user', 'permission'),)


class DjangoAdminLog(models.Model):
    action_time = models.DateTimeField()
    object_id = models.TextField(blank=True, null=True)
    object_repr = models.CharField(max_length=200)
    change_message = models.TextField()
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING, blank=True, null=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    action_flag = models.PositiveSmallIntegerField()

    class Meta:
        managed = False
        db_table = 'django_admin_log'


class DjangoContentType(models.Model):
    app_label = models.CharField(max_length=100)
    model = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'django_content_type'
        unique_together = (('app_label', 'model'),)


class DjangoMigrations(models.Model):
    app = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    applied = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_migrations'


class DjangoSession(models.Model):
    session_key = models.CharField(primary_key=True, max_length=40)
    session_data = models.TextField()
    expire_date = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_session'


class TestingClaims(models.Model):
    field1 = models.TextField(blank=True, null=True)
    field2 = models.TextField(blank=True, null=True)
    field3 = models.TextField(blank=True, null=True)
    field4 = models.TextField(blank=True, null=True)
    field5 = models.TextField(blank=True, null=True)
    field6 = models.TextField(blank=True, null=True)
    field7 = models.TextField(blank=True, null=True)
    field8 = models.TextField(blank=True, null=True)
    field9 = models.TextField(blank=True, null=True)
    field10 = models.TextField(blank=True, null=True)
    field11 = models.TextField(blank=True, null=True)
    field12 = models.TextField(blank=True, null=True)
    field13 = models.TextField(blank=True, null=True)
    field14 = models.TextField(blank=True, null=True)
    field15 = models.TextField(blank=True, null=True)
    field16 = models.TextField(blank=True, null=True)
    field17 = models.TextField(blank=True, null=True)
    field18 = models.TextField(blank=True, null=True)
    field19 = models.TextField(blank=True, null=True)
    field20 = models.TextField(blank=True, null=True)
    field21 = models.TextField(blank=True, null=True)
    field22 = models.TextField(blank=True, null=True)
    field23 = models.TextField(blank=True, null=True)
    field24 = models.TextField(blank=True, null=True)
    field25 = models.TextField(blank=True, null=True)
    field26 = models.TextField(blank=True, null=True)
    field27 = models.TextField(blank=True, null=True)
    field28 = models.TextField(blank=True, null=True)
    field29 = models.TextField(blank=True, null=True)
    field30 = models.TextField(blank=True, null=True)
    field31 = models.TextField(blank=True, null=True)
    field32 = models.TextField(blank=True, null=True)
    field33 = models.TextField(blank=True, null=True)
    field34 = models.TextField(blank=True, null=True)
    field35 = models.TextField(blank=True, null=True)
    field36 = models.TextField(blank=True, null=True)
    field37 = models.TextField(blank=True, null=True)
    field38 = models.TextField(blank=True, null=True)
    field39 = models.TextField(blank=True, null=True)
    field40 = models.TextField(blank=True, null=True)
    field41 = models.TextField(blank=True, null=True)
    field42 = models.TextField(blank=True, null=True)
    field43 = models.TextField(blank=True, null=True)
    field44 = models.TextField(blank=True, null=True)
    field45 = models.TextField(blank=True, null=True)
    field46 = models.TextField(blank=True, null=True)
    field47 = models.TextField(blank=True, null=True)
    field48 = models.TextField(blank=True, null=True)
    field49 = models.TextField(blank=True, null=True)
    field50 = models.TextField(blank=True, null=True)
    field51 = models.TextField(blank=True, null=True)
    field52 = models.TextField(blank=True, null=True)
    field53 = models.TextField(blank=True, null=True)
    field54 = models.TextField(blank=True, null=True)
    field55 = models.TextField(blank=True, null=True)
    field56 = models.TextField(blank=True, null=True)
    field57 = models.TextField(blank=True, null=True)
    field58 = models.TextField(blank=True, null=True)
    field59 = models.TextField(blank=True, null=True)
    field60 = models.TextField(blank=True, null=True)
    field61 = models.TextField(blank=True, null=True)
    field62 = models.TextField(blank=True, null=True)
    field63 = models.TextField(blank=True, null=True)
    field64 = models.TextField(blank=True, null=True)
    field65 = models.TextField(blank=True, null=True)
    field66 = models.TextField(blank=True, null=True)
    field67 = models.TextField(blank=True, null=True)
    field68 = models.TextField(blank=True, null=True)
    field69 = models.TextField(blank=True, null=True)
    field70 = models.TextField(blank=True, null=True)
    field71 = models.TextField(blank=True, null=True)
    field72 = models.TextField(blank=True, null=True)
    field73 = models.TextField(blank=True, null=True)
    field74 = models.TextField(blank=True, null=True)
    field75 = models.TextField(blank=True, null=True)
    field76 = models.TextField(blank=True, null=True)
    field77 = models.TextField(blank=True, null=True)
    field78 = models.TextField(blank=True, null=True)
    field79 = models.TextField(blank=True, null=True)
    field80 = models.TextField(blank=True, null=True)
    field81 = models.TextField(blank=True, null=True)
    field82 = models.TextField(blank=True, null=True)
    field83 = models.TextField(blank=True, null=True)
    field84 = models.TextField(blank=True, null=True)
    field85 = models.TextField(blank=True, null=True)
    field86 = models.TextField(blank=True, null=True)
    field87 = models.TextField(blank=True, null=True)
    field88 = models.TextField(blank=True, null=True)
    field89 = models.TextField(blank=True, null=True)
    field90 = models.TextField(blank=True, null=True)
    field91 = models.TextField(blank=True, null=True)
    field92 = models.TextField(blank=True, null=True)
    field93 = models.TextField(blank=True, null=True)
    field94 = models.TextField(blank=True, null=True)
    field95 = models.TextField(blank=True, null=True)
    field96 = models.TextField(blank=True, null=True)
    field97 = models.TextField(blank=True, null=True)
    field98 = models.TextField(blank=True, null=True)
    field99 = models.TextField(blank=True, null=True)
    field100 = models.TextField(blank=True, null=True)
    field101 = models.TextField(blank=True, null=True)
    field102 = models.TextField(blank=True, null=True)
    field103 = models.TextField(blank=True, null=True)
    field104 = models.TextField(blank=True, null=True)
    field105 = models.TextField(blank=True, null=True)
    field106 = models.TextField(blank=True, null=True)
    field107 = models.TextField(blank=True, null=True)
    field108 = models.TextField(blank=True, null=True)
    field109 = models.TextField(blank=True, null=True)
    field110 = models.TextField(blank=True, null=True)
    field111 = models.TextField(blank=True, null=True)
    field112 = models.TextField(blank=True, null=True)
    field113 = models.TextField(blank=True, null=True)
    field114 = models.TextField(blank=True, null=True)
    field115 = models.TextField(blank=True, null=True)
    field116 = models.TextField(blank=True, null=True)
    field117 = models.TextField(blank=True, null=True)
    field118 = models.TextField(blank=True, null=True)
    field119 = models.TextField(blank=True, null=True)
    field120 = models.TextField(blank=True, null=True)
    field121 = models.TextField(blank=True, null=True)
    field122 = models.TextField(blank=True, null=True)
    field123 = models.TextField(blank=True, null=True)
    field124 = models.TextField(blank=True, null=True)
    field125 = models.TextField(blank=True, null=True)
    field126 = models.TextField(blank=True, null=True)
    field127 = models.TextField(blank=True, null=True)
    field128 = models.TextField(blank=True, null=True)
    field129 = models.TextField(blank=True, null=True)
    field130 = models.TextField(blank=True, null=True)
    field131 = models.TextField(blank=True, null=True)
    field132 = models.TextField(blank=True, null=True)
    field133 = models.TextField(blank=True, null=True)
    field134 = models.TextField(blank=True, null=True)
    field135 = models.TextField(blank=True, null=True)
    field136 = models.TextField(blank=True, null=True)
    field137 = models.TextField(blank=True, null=True)
    field138 = models.TextField(blank=True, null=True)
    field139 = models.TextField(blank=True, null=True)
    field140 = models.TextField(blank=True, null=True)
    field141 = models.TextField(blank=True, null=True)
    field142 = models.TextField(blank=True, null=True)
    field143 = models.TextField(blank=True, null=True)
    field144 = models.TextField(blank=True, null=True)
    field145 = models.TextField(blank=True, null=True)
    field146 = models.TextField(blank=True, null=True)
    field147 = models.TextField(blank=True, null=True)
    field148 = models.TextField(blank=True, null=True)
    field149 = models.TextField(blank=True, null=True)
    field150 = models.TextField(blank=True, null=True)
    field151 = models.TextField(blank=True, null=True)
    field152 = models.TextField(blank=True, null=True)
    field153 = models.TextField(blank=True, null=True)
    field154 = models.TextField(blank=True, null=True)
    field155 = models.TextField(blank=True, null=True)
    field156 = models.TextField(blank=True, null=True)
    field157 = models.TextField(blank=True, null=True)
    field158 = models.TextField(blank=True, null=True)
    field159 = models.TextField(blank=True, null=True)
    field160 = models.TextField(blank=True, null=True)
    field161 = models.TextField(blank=True, null=True)
    field162 = models.TextField(blank=True, null=True)
    field163 = models.TextField(blank=True, null=True)
    field164 = models.TextField(blank=True, null=True)
    field165 = models.TextField(blank=True, null=True)
    field166 = models.TextField(blank=True, null=True)
    field167 = models.TextField(blank=True, null=True)
    field168 = models.TextField(blank=True, null=True)
    field169 = models.TextField(blank=True, null=True)
    field170 = models.TextField(blank=True, null=True)
    field171 = models.TextField(blank=True, null=True)
    field172 = models.TextField(blank=True, null=True)
    field173 = models.TextField(blank=True, null=True)
    field174 = models.TextField(blank=True, null=True)
    field175 = models.TextField(blank=True, null=True)
    field176 = models.TextField(blank=True, null=True)
    field177 = models.TextField(blank=True, null=True)
    field178 = models.TextField(blank=True, null=True)
    field179 = models.TextField(blank=True, null=True)
    field180 = models.TextField(blank=True, null=True)
    field181 = models.TextField(blank=True, null=True)
    field182 = models.TextField(blank=True, null=True)
    field183 = models.TextField(blank=True, null=True)
    field184 = models.TextField(blank=True, null=True)
    field185 = models.TextField(blank=True, null=True)
    field186 = models.TextField(blank=True, null=True)
    field187 = models.TextField(blank=True, null=True)
    field188 = models.TextField(blank=True, null=True)
    field189 = models.TextField(blank=True, null=True)
    field190 = models.TextField(blank=True, null=True)
    field191 = models.TextField(blank=True, null=True)
    field192 = models.TextField(blank=True, null=True)
    field193 = models.TextField(blank=True, null=True)
    field194 = models.TextField(blank=True, null=True)
    field195 = models.TextField(blank=True, null=True)
    field196 = models.TextField(blank=True, null=True)
    field197 = models.TextField(blank=True, null=True)
    field198 = models.TextField(blank=True, null=True)
    field199 = models.TextField(blank=True, null=True)
    field200 = models.TextField(blank=True, null=True)
    field201 = models.TextField(blank=True, null=True)
    field202 = models.TextField(blank=True, null=True)
    field203 = models.TextField(blank=True, null=True)
    field204 = models.TextField(blank=True, null=True)
    field205 = models.TextField(blank=True, null=True)
    field206 = models.TextField(blank=True, null=True)
    field207 = models.TextField(blank=True, null=True)
    field208 = models.TextField(blank=True, null=True)
    field209 = models.TextField(blank=True, null=True)
    field210 = models.TextField(blank=True, null=True)
    field211 = models.TextField(blank=True, null=True)
    field212 = models.TextField(blank=True, null=True)
    field213 = models.TextField(blank=True, null=True)
    field214 = models.TextField(blank=True, null=True)
    field215 = models.TextField(blank=True, null=True)
    field216 = models.TextField(blank=True, null=True)
    field217 = models.TextField(blank=True, null=True)
    field218 = models.TextField(blank=True, null=True)
    field219 = models.TextField(blank=True, null=True)
    field220 = models.TextField(blank=True, null=True)
    field221 = models.TextField(blank=True, null=True)
    field222 = models.TextField(blank=True, null=True)
    field223 = models.TextField(blank=True, null=True)
    field224 = models.TextField(blank=True, null=True)
    field225 = models.TextField(blank=True, null=True)
    field226 = models.TextField(blank=True, null=True)
    field227 = models.TextField(blank=True, null=True)
    field228 = models.TextField(blank=True, null=True)
    field229 = models.TextField(blank=True, null=True)
    field230 = models.TextField(blank=True, null=True)
    field231 = models.TextField(blank=True, null=True)
    field232 = models.TextField(blank=True, null=True)
    field233 = models.TextField(blank=True, null=True)
    field234 = models.TextField(blank=True, null=True)
    field235 = models.TextField(blank=True, null=True)
    field236 = models.TextField(blank=True, null=True)
    field237 = models.TextField(blank=True, null=True)
    field238 = models.TextField(blank=True, null=True)
    field239 = models.TextField(blank=True, null=True)
    field240 = models.TextField(blank=True, null=True)
    field241 = models.TextField(blank=True, null=True)
    field242 = models.TextField(blank=True, null=True)
    field243 = models.TextField(blank=True, null=True)
    field244 = models.TextField(blank=True, null=True)
    field245 = models.TextField(blank=True, null=True)
    field246 = models.TextField(blank=True, null=True)
    field247 = models.TextField(blank=True, null=True)
    field248 = models.TextField(blank=True, null=True)
    field249 = models.TextField(blank=True, null=True)
    field250 = models.TextField(blank=True, null=True)
    field251 = models.TextField(blank=True, null=True)
    field252 = models.TextField(blank=True, null=True)
    field253 = models.TextField(blank=True, null=True)
    field254 = models.TextField(blank=True, null=True)
    field255 = models.TextField(blank=True, null=True)
    field256 = models.TextField(blank=True, null=True)
    field257 = models.TextField(blank=True, null=True)
    field258 = models.TextField(blank=True, null=True)
    field259 = models.TextField(blank=True, null=True)
    field260 = models.TextField(blank=True, null=True)
    field261 = models.TextField(blank=True, null=True)
    field262 = models.TextField(blank=True, null=True)
    field263 = models.TextField(blank=True, null=True)
    field264 = models.TextField(blank=True, null=True)
    field265 = models.TextField(blank=True, null=True)
    field266 = models.TextField(blank=True, null=True)
    field267 = models.TextField(blank=True, null=True)
    field268 = models.TextField(blank=True, null=True)
    field269 = models.TextField(blank=True, null=True)
    field270 = models.TextField(blank=True, null=True)
    field271 = models.TextField(blank=True, null=True)
    field272 = models.TextField(blank=True, null=True)
    field273 = models.TextField(blank=True, null=True)
    field274 = models.TextField(blank=True, null=True)
    field275 = models.TextField(blank=True, null=True)
    field276 = models.TextField(blank=True, null=True)
    field277 = models.TextField(blank=True, null=True)
    field278 = models.TextField(blank=True, null=True)
    field279 = models.TextField(blank=True, null=True)
    field280 = models.TextField(blank=True, null=True)
    field281 = models.TextField(blank=True, null=True)
    field282 = models.TextField(blank=True, null=True)
    field283 = models.TextField(blank=True, null=True)
    field284 = models.TextField(blank=True, null=True)
    field285 = models.TextField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'testing_claims'


class TestingElig(models.Model):
    field1 = models.TextField(blank=True, null=True)
    field2 = models.TextField(blank=True, null=True)
    field3 = models.TextField(blank=True, null=True)
    field4 = models.TextField(blank=True, null=True)
    field5 = models.TextField(blank=True, null=True)
    field6 = models.TextField(blank=True, null=True)
    field7 = models.TextField(blank=True, null=True)
    field8 = models.TextField(blank=True, null=True)
    field9 = models.TextField(blank=True, null=True)
    field10 = models.TextField(blank=True, null=True)
    field11 = models.TextField(blank=True, null=True)
    field12 = models.TextField(blank=True, null=True)
    field13 = models.TextField(blank=True, null=True)
    field14 = models.TextField(blank=True, null=True)
    field15 = models.TextField(blank=True, null=True)
    field16 = models.TextField(blank=True, null=True)
    field17 = models.TextField(blank=True, null=True)
    field18 = models.TextField(blank=True, null=True)
    field19 = models.TextField(blank=True, null=True)
    field20 = models.TextField(blank=True, null=True)
    field21 = models.TextField(blank=True, null=True)
    field22 = models.TextField(blank=True, null=True)
    field23 = models.TextField(blank=True, null=True)
    field24 = models.TextField(blank=True, null=True)
    field25 = models.TextField(blank=True, null=True)
    field26 = models.TextField(blank=True, null=True)
    field27 = models.TextField(blank=True, null=True)
    field28 = models.TextField(blank=True, null=True)
    field29 = models.TextField(blank=True, null=True)
    field30 = models.TextField(blank=True, null=True)
    field31 = models.TextField(blank=True, null=True)
    field32 = models.TextField(blank=True, null=True)
    field33 = models.TextField(blank=True, null=True)
    field34 = models.TextField(blank=True, null=True)
    field35 = models.TextField(blank=True, null=True)
    field36 = models.TextField(blank=True, null=True)
    field37 = models.TextField(blank=True, null=True)
    field38 = models.TextField(blank=True, null=True)
    field39 = models.TextField(blank=True, null=True)
    field40 = models.TextField(blank=True, null=True)
    field41 = models.TextField(blank=True, null=True)
    field42 = models.TextField(blank=True, null=True)
    field43 = models.TextField(blank=True, null=True)
    field44 = models.TextField(blank=True, null=True)
    field45 = models.TextField(blank=True, null=True)
    field46 = models.TextField(blank=True, null=True)
    field47 = models.TextField(blank=True, null=True)
    field48 = models.TextField(blank=True, null=True)
    field49 = models.TextField(blank=True, null=True)
    field50 = models.TextField(blank=True, null=True)
    field51 = models.TextField(blank=True, null=True)
    field52 = models.TextField(blank=True, null=True)
    field53 = models.TextField(blank=True, null=True)
    field54 = models.TextField(blank=True, null=True)
    field55 = models.TextField(blank=True, null=True)
    field56 = models.TextField(blank=True, null=True)
    field57 = models.TextField(blank=True, null=True)
    field58 = models.TextField(blank=True, null=True)
    field59 = models.TextField(blank=True, null=True)
    field60 = models.TextField(blank=True, null=True)
    field61 = models.TextField(blank=True, null=True)
    field62 = models.TextField(blank=True, null=True)
    field63 = models.TextField(blank=True, null=True)
    field64 = models.TextField(blank=True, null=True)
    field65 = models.TextField(blank=True, null=True)
    field66 = models.TextField(blank=True, null=True)
    field67 = models.TextField(blank=True, null=True)
    field68 = models.TextField(blank=True, null=True)
    field69 = models.TextField(blank=True, null=True)
    field70 = models.TextField(blank=True, null=True)
    field71 = models.TextField(blank=True, null=True)
    field72 = models.TextField(blank=True, null=True)
    field73 = models.TextField(blank=True, null=True)
    field74 = models.TextField(blank=True, null=True)
    field75 = models.TextField(blank=True, null=True)
    field76 = models.TextField(blank=True, null=True)
    field77 = models.TextField(blank=True, null=True)
    field78 = models.TextField(blank=True, null=True)
    field79 = models.TextField(blank=True, null=True)
    field80 = models.TextField(blank=True, null=True)
    field81 = models.TextField(blank=True, null=True)
    field82 = models.TextField(blank=True, null=True)
    field83 = models.TextField(blank=True, null=True)
    field84 = models.TextField(blank=True, null=True)
    field85 = models.TextField(blank=True, null=True)
    field86 = models.TextField(blank=True, null=True)
    field87 = models.TextField(blank=True, null=True)
    field88 = models.TextField(blank=True, null=True)
    field89 = models.TextField(blank=True, null=True)
    field90 = models.TextField(blank=True, null=True)
    field91 = models.TextField(blank=True, null=True)
    field92 = models.TextField(blank=True, null=True)
    field93 = models.TextField(blank=True, null=True)
    field94 = models.TextField(blank=True, null=True)
    field95 = models.TextField(blank=True, null=True)
    field96 = models.TextField(blank=True, null=True)
    field97 = models.TextField(blank=True, null=True)
    field98 = models.TextField(blank=True, null=True)
    field99 = models.TextField(blank=True, null=True)
    field100 = models.TextField(blank=True, null=True)
    field101 = models.TextField(blank=True, null=True)
    field102 = models.TextField(blank=True, null=True)
    field103 = models.TextField(blank=True, null=True)
    field104 = models.TextField(blank=True, null=True)
    field105 = models.TextField(blank=True, null=True)
    field106 = models.TextField(blank=True, null=True)
    field107 = models.TextField(blank=True, null=True)
    field108 = models.TextField(blank=True, null=True)
    field109 = models.TextField(blank=True, null=True)
    field110 = models.TextField(blank=True, null=True)
    field111 = models.TextField(blank=True, null=True)
    field112 = models.TextField(blank=True, null=True)
    field113 = models.TextField(blank=True, null=True)
    field114 = models.TextField(blank=True, null=True)
    field115 = models.TextField(blank=True, null=True)
    field116 = models.TextField(blank=True, null=True)
    field117 = models.TextField(blank=True, null=True)
    field118 = models.TextField(blank=True, null=True)
    field119 = models.TextField(blank=True, null=True)
    field120 = models.TextField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'testing_elig'


class TestingRxclaims(models.Model):
    field1 = models.TextField(blank=True, null=True)
    field2 = models.TextField(blank=True, null=True)
    field3 = models.TextField(blank=True, null=True)
    field4 = models.TextField(blank=True, null=True)
    field5 = models.TextField(blank=True, null=True)
    field6 = models.TextField(blank=True, null=True)
    field7 = models.TextField(blank=True, null=True)
    field8 = models.TextField(blank=True, null=True)
    field9 = models.TextField(blank=True, null=True)
    field10 = models.TextField(blank=True, null=True)
    field11 = models.TextField(blank=True, null=True)
    field12 = models.TextField(blank=True, null=True)
    field13 = models.TextField(blank=True, null=True)
    field14 = models.TextField(blank=True, null=True)
    field15 = models.TextField(blank=True, null=True)
    field16 = models.TextField(blank=True, null=True)
    field17 = models.TextField(blank=True, null=True)
    field18 = models.TextField(blank=True, null=True)
    field19 = models.TextField(blank=True, null=True)
    field20 = models.TextField(blank=True, null=True)
    field21 = models.TextField(blank=True, null=True)
    field22 = models.TextField(blank=True, null=True)
    field23 = models.TextField(blank=True, null=True)
    field24 = models.TextField(blank=True, null=True)
    field25 = models.TextField(blank=True, null=True)
    field26 = models.TextField(blank=True, null=True)
    field27 = models.TextField(blank=True, null=True)
    field28 = models.TextField(blank=True, null=True)
    field29 = models.TextField(blank=True, null=True)
    field30 = models.TextField(blank=True, null=True)
    field31 = models.TextField(blank=True, null=True)
    field32 = models.TextField(blank=True, null=True)
    field33 = models.TextField(blank=True, null=True)
    field34 = models.TextField(blank=True, null=True)
    field35 = models.TextField(blank=True, null=True)
    field36 = models.TextField(blank=True, null=True)
    field37 = models.TextField(blank=True, null=True)
    field38 = models.TextField(blank=True, null=True)
    field39 = models.TextField(blank=True, null=True)
    field40 = models.TextField(blank=True, null=True)
    field41 = models.TextField(blank=True, null=True)
    field42 = models.TextField(blank=True, null=True)
    field43 = models.TextField(blank=True, null=True)
    field44 = models.TextField(blank=True, null=True)
    field45 = models.TextField(blank=True, null=True)
    field46 = models.TextField(blank=True, null=True)
    field47 = models.TextField(blank=True, null=True)
    field48 = models.TextField(blank=True, null=True)
    field49 = models.TextField(blank=True, null=True)
    field50 = models.TextField(blank=True, null=True)
    field51 = models.TextField(blank=True, null=True)
    field52 = models.TextField(blank=True, null=True)
    field53 = models.TextField(blank=True, null=True)
    field54 = models.TextField(blank=True, null=True)
    field55 = models.TextField(blank=True, null=True)
    field56 = models.TextField(blank=True, null=True)
    field57 = models.TextField(blank=True, null=True)
    field58 = models.TextField(blank=True, null=True)
    field59 = models.TextField(blank=True, null=True)
    field60 = models.TextField(blank=True, null=True)
    field61 = models.TextField(blank=True, null=True)
    field62 = models.TextField(blank=True, null=True)
    field63 = models.TextField(blank=True, null=True)
    field64 = models.TextField(blank=True, null=True)
    field65 = models.TextField(blank=True, null=True)
    field66 = models.TextField(blank=True, null=True)
    field67 = models.TextField(blank=True, null=True)
    field68 = models.TextField(blank=True, null=True)
    field69 = models.TextField(blank=True, null=True)
    field70 = models.TextField(blank=True, null=True)
    field71 = models.TextField(blank=True, null=True)
    field72 = models.TextField(blank=True, null=True)
    field73 = models.TextField(blank=True, null=True)
    field74 = models.TextField(blank=True, null=True)
    field75 = models.TextField(blank=True, null=True)
    field76 = models.TextField(blank=True, null=True)
    field77 = models.TextField(blank=True, null=True)
    field78 = models.TextField(blank=True, null=True)
    field79 = models.TextField(blank=True, null=True)
    field80 = models.TextField(blank=True, null=True)
    field81 = models.TextField(blank=True, null=True)
    field82 = models.TextField(blank=True, null=True)
    field83 = models.TextField(blank=True, null=True)
    field84 = models.TextField(blank=True, null=True)
    field85 = models.TextField(blank=True, null=True)
    field86 = models.TextField(blank=True, null=True)
    field87 = models.TextField(blank=True, null=True)
    field88 = models.TextField(blank=True, null=True)
    field89 = models.TextField(blank=True, null=True)
    field90 = models.TextField(blank=True, null=True)
    field91 = models.TextField(blank=True, null=True)
    field92 = models.TextField(blank=True, null=True)
    field93 = models.TextField(blank=True, null=True)
    field94 = models.TextField(blank=True, null=True)
    field95 = models.TextField(blank=True, null=True)
    field96 = models.TextField(blank=True, null=True)
    field97 = models.TextField(blank=True, null=True)
    field98 = models.TextField(blank=True, null=True)
    field99 = models.TextField(blank=True, null=True)
    field100 = models.TextField(blank=True, null=True)
    field101 = models.TextField(blank=True, null=True)
    field102 = models.TextField(blank=True, null=True)
    field103 = models.TextField(blank=True, null=True)
    field104 = models.TextField(blank=True, null=True)
    field105 = models.TextField(blank=True, null=True)
    field106 = models.TextField(blank=True, null=True)
    field107 = models.TextField(blank=True, null=True)
    field108 = models.TextField(blank=True, null=True)
    field109 = models.TextField(blank=True, null=True)
    field110 = models.TextField(blank=True, null=True)
    field111 = models.TextField(blank=True, null=True)
    field112 = models.TextField(blank=True, null=True)
    field113 = models.TextField(blank=True, null=True)
    field114 = models.TextField(blank=True, null=True)
    field115 = models.TextField(blank=True, null=True)
    field116 = models.TextField(blank=True, null=True)
    field117 = models.TextField(blank=True, null=True)
    field118 = models.TextField(blank=True, null=True)
    field119 = models.TextField(blank=True, null=True)
    field120 = models.TextField(blank=True, null=True)
    field121 = models.TextField(blank=True, null=True)
    field122 = models.TextField(blank=True, null=True)
    field123 = models.TextField(blank=True, null=True)
    field124 = models.TextField(blank=True, null=True)
    field125 = models.TextField(blank=True, null=True)
    field126 = models.TextField(blank=True, null=True)
    field127 = models.TextField(blank=True, null=True)
    field128 = models.TextField(blank=True, null=True)
    field129 = models.TextField(blank=True, null=True)
    field130 = models.TextField(blank=True, null=True)
    field131 = models.TextField(blank=True, null=True)
    field132 = models.TextField(blank=True, null=True)
    field133 = models.TextField(blank=True, null=True)
    field134 = models.TextField(blank=True, null=True)
    field135 = models.TextField(blank=True, null=True)
    field136 = models.TextField(blank=True, null=True)
    field137 = models.TextField(blank=True, null=True)
    field138 = models.TextField(blank=True, null=True)
    field139 = models.TextField(blank=True, null=True)
    field140 = models.TextField(blank=True, null=True)
    field141 = models.TextField(blank=True, null=True)
    field142 = models.TextField(blank=True, null=True)
    field143 = models.TextField(blank=True, null=True)
    field144 = models.TextField(blank=True, null=True)
    field145 = models.TextField(blank=True, null=True)
    field146 = models.TextField(blank=True, null=True)
    field147 = models.TextField(blank=True, null=True)
    field148 = models.TextField(blank=True, null=True)
    field149 = models.TextField(blank=True, null=True)
    field150 = models.TextField(blank=True, null=True)
    field151 = models.TextField(blank=True, null=True)
    field152 = models.TextField(blank=True, null=True)
    field153 = models.TextField(blank=True, null=True)
    field154 = models.TextField(blank=True, null=True)
    field155 = models.TextField(blank=True, null=True)
    field156 = models.TextField(blank=True, null=True)
    field157 = models.TextField(blank=True, null=True)
    field158 = models.TextField(blank=True, null=True)
    field159 = models.TextField(blank=True, null=True)
    field160 = models.TextField(blank=True, null=True)
    field161 = models.TextField(blank=True, null=True)
    field162 = models.TextField(blank=True, null=True)
    field163 = models.TextField(blank=True, null=True)
    field164 = models.TextField(blank=True, null=True)
    field165 = models.TextField(blank=True, null=True)
    field166 = models.TextField(blank=True, null=True)
    field167 = models.TextField(blank=True, null=True)
    field168 = models.TextField(blank=True, null=True)
    field169 = models.TextField(blank=True, null=True)
    field170 = models.TextField(blank=True, null=True)
    field171 = models.TextField(blank=True, null=True)
    field172 = models.TextField(blank=True, null=True)
    field173 = models.TextField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'testing_rxclaims'
